
seedData = [
    {
        "user_id": 1001,
        "first_name": "Liam",
        "last_name": "Chen",
        "email": "liam.chen@fakeshop.com",
        "phone_number": "(555) 123-4567",
        "password_hash": "Hello123$",

        "date_joined": "2024-01-15",
        "loyalty_tier": "GOLD",
        "is_active": true,
    },
    {
        "user_id": 1002,
        "first_name": "Olivia",
        "last_name": "Baker",
        "email": "olivia.baker@fakeshop.com",
        "phone_number": "(555) 234-5678",
        "password_hash": "Hello123$",
        "date_joined": "2023-08-22",
        "loyalty_tier": "SILVER",
        "is_active": true,
    },
    {
        "user_id": 1003,
        "first_name": "Noah",
        "last_name": "Patel",
        "email": "noah.patel@fakeshop.com",
        "phone_number": "(555) 345-6789",
        "password_hash": "Hello123$",
        "date_joined": "2025-02-10",
        "loyalty_tier": "BRONZE",
        "is_active": true,
    },
    {
        "user_id": 1004,
        "first_name": "Emma",
        "last_name": "Kim",
        "email": "emma.kim@fakeshop.com",
        "password_hash": "Hello123$",
        "phone_number": "(555) 456-7890",
        "date_joined": "2022-05-01",
        "is_active": false,
    },
    {
        "user_id": 1005,
        "first_name": "Jackson",
        "last_name": "White",
        "email": "jackson.white@fakeshop.com",
        "phone_number": "(555) 567-8901",
        "password_hash": "Hello123$",

        "date_joined": "2024-11-30",
        "is_active": true,
    },
    {
        "user_id": 1006,
        "first_name": "Ava",
        "last_name": "Sharma",
        "email": "ava.sharma@fakeshop.com",
        "password_hash": "Hello123$",

        "phone_number": "(555) 678-9012",
        "date_joined": "2023-01-05",
        "is_active": true,
    },
    {
        "user_id": 1007,
        "first_name": "Lucas",
        "last_name": "Johnson",
        "email": "lucas.johnson@fakeshop.com",
        "phone_number": "(555) 789-0123",
        "password_hash": "Hello123$",
        "date_joined": "2025-06-18",
        "loyalty_tier": "BRONZE",
        "is_active": true,
    },
    {
        "user_id": 1008,
        "first_name": "Mia",
        "last_name": "Rodriguez",
        "email": "mia.rodriguez@fakeshop.com",
        "phone_number": "(555) 890-1234",
        "password_hash": "Hello123$",
        "date_joined": "2024-04-03",
        "is_active": true,
    },
    {
        "user_id": 1009,
        "first_name": "Ethan",
        "last_name": "Wong",
        "email": "ethan.wong@fakeshop.com",
        "phone_number": "(555) 901-2345",
        "password_hash": "Hello123$",

        "date_joined": "2022-12-01",
        "loyalty_tier": "GOLD",
        "is_active": false,
    },
    {
        "user_id": 1010,
        "first_name": "Sophia",
        "last_name": "Miller",
        "email": "sophia.miller@fakeshop.com",
        "phone_number": "(555) 012-3456",
        "password_hash": "Hello123$",
        "date_joined": "2025-07-25",
        "loyalty_tier": "SILVER",
        "is_active": true,
    }
]

module.exports = seedData